"""Create network observations table

Revision ID: 6ed5fcf4c207
Revises: 
Create Date: 2026-09-10 21:33:43.770224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed5fcf4c207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_ip', sa.String(length=45), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network_observations')
    # ### end Alembic commands ###
